CREATE TABLE IF NOT EXISTS quick_assessments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    assessment_number VARCHAR(20) UNIQUE NOT NULL,
    assessment_date DATE NOT NULL,
    car_id INT NULL,
    car_make VARCHAR(100),
    car_model VARCHAR(100),
    car_registration VARCHAR(50),
    car_year INT,
    client_id INT NULL,
    client_name VARCHAR(150),
    client_phone VARCHAR(50),
    service_booking_id INT NULL,
    check_tyres ENUM('ok','issue','na') DEFAULT 'na',
    check_lights ENUM('ok','issue','na') DEFAULT 'na',
    check_exterior ENUM('ok','issue','na') DEFAULT 'na',
    check_engine ENUM('ok','issue','na') DEFAULT 'na',
    check_interior ENUM('ok','issue','na') DEFAULT 'na',
    check_brakes ENUM('ok','issue','na') DEFAULT 'na',
    check_fluids ENUM('ok','issue','na') DEFAULT 'na',
    check_electrical ENUM('ok','issue','na') DEFAULT 'na',
    overall_condition ENUM('good','fair','needs_attention','critical') DEFAULT 'fair',
    observations TEXT,
    recommended_services TEXT,
    assessed_by VARCHAR(100),
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (car_id) REFERENCES cars(id) ON DELETE SET NULL,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
    FOREIGN KEY (service_booking_id) REFERENCES service_bookings(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
