CREATE TABLE IF NOT EXISTS payments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    payment_number VARCHAR(20) UNIQUE NOT NULL,
    payment_date DATE NOT NULL,
    client_id INT NULL,
    client_name VARCHAR(150) NOT NULL,
    client_phone VARCHAR(50),
    invoice_id INT NULL,
    service_booking_id INT NULL,
    description TEXT,
    amount DECIMAL(12,2) NOT NULL,
    payment_method ENUM('mpesa','bank','cheque','cash') NOT NULL,
    reference_number VARCHAR(100),
    mpesa_phone VARCHAR(50),
    mpesa_name VARCHAR(150),
    bank_name VARCHAR(100),
    account_number VARCHAR(100),
    cheque_number VARCHAR(100),
    cheque_date DATE NULL,
    notes TEXT,
    balance_adjustment DECIMAL(12,2) DEFAULT 0,
    status ENUM('pending','confirmed','reversed') DEFAULT 'pending',
    recorded_by VARCHAR(100),
    confirmed_by VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL,
    FOREIGN KEY (service_booking_id) REFERENCES service_bookings(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
